#pragma once

static const char PLAYER_PAGE[] PROGMEM = R"HTML(
<!doctype html><html lang="ru"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>WIGO · Бункер</title>
<style>
:root{color-scheme:dark;--bg:#0b1118;--panel:#141e29;--edge:#263748;--mint:#72edc5;--text:#eff6f5;--muted:#9aabb7;--gold:#ffd782}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(ellipse at 50% -20%,#254238 0,#0b1118 52%);color:var(--text);font:16px system-ui,sans-serif;min-height:100vh}
main{max-width:620px;margin:auto;padding:22px 16px 48px}.brand{font-size:13px;letter-spacing:.2em;color:var(--mint);font-weight:800}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}h1{font-size:30px;margin:5px 0 0}h2{font-size:20px;margin:0 0 14px}.status{font-size:13px;color:var(--muted);text-align:right}
section{background:linear-gradient(145deg,#172331,#111923);border:1px solid var(--edge);border-radius:18px;padding:18px;margin:14px 0;box-shadow:0 10px 26px #0003}.eyebrow{color:var(--mint);text-transform:uppercase;letter-spacing:.13em;font-size:11px;font-weight:800}
input,button{font:inherit;border-radius:12px;padding:12px 14px}input{width:100%;background:#0a121a;border:1px solid var(--edge);color:var(--text);margin:8px 0}button{border:0;background:var(--mint);color:#092019;font-weight:800;cursor:pointer}button.secondary{background:#263748;color:var(--text)}button:active{transform:translateY(1px)}.row{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.row button{flex:1}
.player-list{display:grid;gap:7px;margin:12px 0}.player{display:flex;justify-content:space-between;background:#0d1721;border:1px solid #223241;border-radius:11px;padding:10px 12px}.tag{font-size:12px;color:var(--mint)}.tag.wait{color:var(--gold)}
.scenario{border-color:#604a2a;background:linear-gradient(145deg,#302718,#171b20)}.scenario h2{color:var(--gold);margin-top:5px}.scenario p{line-height:1.5;color:#e2e4de}.meta{display:flex;gap:8px;flex-wrap:wrap}.pill{border:1px solid #6a5733;border-radius:999px;padding:6px 10px;color:#ffe3a4;font-size:13px}
.phase{display:flex;align-items:center;justify-content:space-between;gap:12px}.phase strong{font-size:18px}.round{color:var(--muted);font-size:13px}
.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.trait{background:#0c151e;border:1px solid #253848;border-radius:13px;padding:12px;min-height:84px}.trait span{display:block;color:var(--mint);font-size:11px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:7px}.trait strong{font-size:14px;line-height:1.35;font-weight:650}
.vote-list{display:grid;gap:8px}.vote-list button{width:100%;text-align:left}.result{text-align:center;padding:27px 18px}.result.win{border-color:#39795f}.result.loss{border-color:#8b4449}.result h2{font-size:28px}.result.win h2{color:var(--mint)}.result.loss h2{color:#ff9198}.result p{line-height:1.5;color:#ccd6dc}.small{font-size:13px;color:var(--muted)}[hidden]{display:none!important}
.boardGrid{display:grid;gap:12px}.playerBoard{border:1px solid #2c4051;border-radius:15px;padding:13px;background:#0d1721}.playerBoard.currentTurn{border-color:var(--gold);box-shadow:0 0 0 2px #ffd78230}.playerBoard h3{margin:0 0 10px;display:flex;justify-content:space-between}.cardGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.cardBack,.cardOpen{min-height:64px;border-radius:11px;padding:9px;text-align:left}.cardBack{background:linear-gradient(145deg,#293a4a,#172431);border:1px solid #40566b;color:#b6c8d6}.cardBack strong,.cardOpen strong{display:block;font-size:12px}.cardBack span,.cardOpen span{display:block;font-size:10px;color:var(--mint);margin-bottom:5px}.cardOpen{background:#13261f;border:1px solid #37614f;color:var(--text);cursor:default}.queue{padding:10px 12px;background:#0b151d;border-radius:12px;line-height:1.5;color:#d9e6e6}
.turnNotice{padding:13px;border-radius:13px;background:#31291a;border:1px solid #715b30;color:#ffe3a4;line-height:1.5;margin:12px 0}.cardBack.canReveal{background:linear-gradient(145deg,#35624f,#18392f);border:2px solid var(--mint);color:#f2fff9;cursor:pointer;text-align:center}.cardBack.canReveal strong{font-size:13px}.cardBack.waiting{cursor:default}
.roleCard{border-color:#9c464b;background:linear-gradient(145deg,#381e25,#181821);margin:12px 0}.roleCard span{color:#ffabb1}.roleCard strong{font-size:25px;letter-spacing:.03em}.roleCard p{margin-bottom:0;line-height:1.45}.hostRoleCard{background:linear-gradient(145deg,#202b39,#101821);border:1px solid #425267;border-radius:12px;padding:11px}.hostRoleCard span{display:block;color:var(--mint);font-size:11px;margin-bottom:5px}.hostRoleCard strong{font-size:15px}
@media(max-width:420px){main{padding:16px 12px 34px}.cards{gap:7px}.trait{padding:10px}.trait strong{font-size:13px}section{padding:15px}}
</style></head><body><main>
<header class="top"><div><div class="brand">WIGO · ПЛАТФОРМА ИГР</div><h1 id="title">Загрузка игры…</h1></div><div id="status" class="status">Подключение…</div></header>
<section id="join"><div class="eyebrow">Вход в комнату</div><input id="name" maxlength="16" placeholder="Ваше имя"><button onclick="joinRoom()">Войти</button></section>
<section id="lobby" hidden><div class="eyebrow">Комната <span id="room">----</span></div><h2>Состав команды</h2><div id="players" class="player-list"></div><div id="whoSubmit" hidden><p class="small">Придумай персонажа для каждого другого участника. Себе придумывать не нужно: свою карточку никто не получит.</p><div id="whoTargets"></div><button id="whoSubmitButton" class="secondary" onclick="submitWhoCards()">Отправить персонажей</button><p id="whoCardStatus" class="small"></p></div><p id="minimumPlayers" class="small">Подготовка игры…</p><div class="row"><button id="readyButton" onclick="send('READY')">Готов</button><button class="secondary" onclick="send('START')">Начать игру</button></div></section>
<section id="scenario" class="scenario" hidden><div class="eyebrow">Сценарий катастрофы</div><h2 id="scenarioTitle"></h2><p id="scenarioDescription"></p><div class="meta"><span id="capacity" class="pill"></span></div></section>
<section id="game" hidden><div class="phase"><div><div class="eyebrow">Текущий этап</div><strong id="phaseName">Обсуждение</strong></div><div id="round" class="round"></div></div><div id="turnNotice" class="turnNotice" hidden></div><h2 style="margin-top:20px">Твои карточки</h2><div id="profile" class="cards"></div><div class="row"><button class="secondary" onclick="send('LOOK')">Открыть карточки игроков и очередь</button></div><div id="hostAction" class="row"><button onclick="send('NEXT')">Завершить обсуждение и открыть голосование</button></div><div id="votes" class="vote-list"></div><p id="feedback" class="small"></p></section>
<section id="crocodileGame" hidden><div class="eyebrow">Одиночный раунд · 30 секунд</div><h2>Покажи слово людям рядом</h2><p class="small">Не произноси слово и его части. Пусть зрители угадывают вслух.</p><div id="crocWord" class="trait"><span>ТВОЁ СЛОВО</span><strong>Ждём начала…</strong></div><div class="phase"><strong id="crocTimer">30</strong><span id="crocScore" class="round">Угадано: 0</span></div><div class="row"><button onclick="send('CROCO:GOT')">Угадали!</button><button class="secondary" onclick="send('CROCO:PASS')">Пропустить</button><button class="secondary" onclick="send('CROCO:END')">Завершить</button></div><p id="crocProgress" class="small"></p></section>
<section id="aliasGame" hidden><div class="eyebrow">Алиас · один телефон · 60 секунд</div><h2>Объясни слово словами</h2><p class="small">Передавайте телефон объясняющему. Нельзя произносить слово или его части; жестами не показывай.</p><div id="aliasWord" class="trait"><span>СЕКРЕТНОЕ СЛОВО</span><strong>Ждём начала…</strong></div><div class="phase"><strong id="aliasTimer">60</strong><span id="aliasScore" class="round">Угадано: 0</span></div><div class="row"><button onclick="send('ALIAS:GOT')">Угадали!</button><button class="secondary" onclick="send('ALIAS:PASS')">Пропустить</button><button class="secondary" onclick="send('ALIAS:END')">Завершить</button></div><p id="aliasProgress" class="small"></p></section>
<section id="mafiaGame" hidden><div class="eyebrow">Твоя секретная карточка</div><article class="trait roleCard"><span>РОЛЬ В ИГРЕ</span><strong id="mafiaRole">Ожидание роли…</strong><p id="mafiaHelp" class="small">Карточку видишь только ты.</p></article><div class="phase"><strong id="mafiaPhase">Ночь</strong><span id="mafiaRound" class="round"></span></div><p class="small">Ведущий вручную переключает ночь и день. Голосование проводится только днём; приложение считает голоса и отмечает выбывших.</p><div id="mafiaHostAction" class="row" hidden></div><div id="mafiaActions" class="vote-list"></div><div id="hostPanel" hidden><h2>Карточки ведущего</h2><p class="small">Все роли видны только тебе. Не показывай этот экран игрокам.</p><div id="mafiaHostRoles" class="player-list"></div><div id="hostReminder" class="turnNotice" hidden></div></div><p id="mafiaFeedback" class="small"></p></section>
<section id="spyGame" hidden><div class="eyebrow">Кто шпион? · обсуждение и голосование</div><article class="trait roleCard"><span>ТВОЯ СЕКРЕТНАЯ КАРТОЧКА</span><strong id="spyRole">Ожидание роли…</strong><p id="spySecret" class="small">Не показывай карточку другим игрокам.</p></article><div class="phase"><strong id="spyPhase">Обсуждение</strong><span id="spyRound" class="round"></span></div><p class="small">Все игроки, кроме шпиона, знают одно место. Задавайте вопросы по очереди и попробуйте найти шпиона. Ведущий открывает голосование.</p><div id="spyHostAction" class="row" hidden></div><div id="spyActions" class="vote-list"></div><p id="spyFeedback" class="small"></p></section>
<section id="whoamiGame" hidden><div class="eyebrow">Кто я? · экран для остальных игроков</div><h2 id="whoamiTitle">Подготовь телефон</h2><p id="whoamiHelp">Нажми кнопку, переверни телефон экраном к остальным и поднеси его ко лбу. Через 5 секунд появится персонаж — не подглядывай!</p><article id="whoamiCard" class="trait roleCard"><span>ТВОЙ ПЕРСОНАЖ</span><strong id="whoamiWord">Сначала подготовь телефон</strong></article><div class="row"><button id="whoamiStart" onclick="send('WHO_START')">Поставить телефон ко лбу</button></div><p id="whoamiCountdown" class="small" aria-live="polite"></p></section>
<section id="boardSection" hidden><div class="phase"><h2>Карточки игроков</h2><button class="secondary" onclick="$('boardSection').hidden=true">Скрыть</button></div><p id="revealQueue" class="queue"></p><div id="cardBoard" class="boardGrid"></div></section>
<section id="finished" class="result" hidden><div id="resultIcon" class="eyebrow"></div><h2 id="resultTitle"></h2><p id="resultMessage"></p><div id="winners" class="player-list"></div><button class="secondary" onclick="send('RESET')">Вернуться в лобби</button></section>
<script>
let ws,token=sessionStorage.getItem('wigo-token')||'',savedName=sessionStorage.getItem('wigo-name')||'',currentRoom=sessionStorage.getItem('wigo-room')||'',reconnecting=!!token,joined=false,selfId=-1,lastState=null,boardOpen=false,mafiaHostRoles=[],whoCardSent=false,whoRosterKey='';let whoCountdownTimer=0;const revealedCards={};const cardNames=['Профессия','Возраст и пол','Здоровье','Хобби','Фобия','Багаж','Факт','Особенность'];const $=id=>document.getElementById(id);
function connect(){ws=new WebSocket('ws://'+location.hostname+':81/');ws.onopen=()=>{$('status').textContent='Связь с WIGO установлена'};
ws.onclose=e=>{joined=false;reconnecting=true;$('status').textContent='Связь потеряна (код '+e.code+'). Переподключение…';setTimeout(connect,1500)};
ws.onerror=()=>{$('status').textContent='Ошибка WebSocket-соединения'};
ws.onmessage=e=>{let m=e.data.split('|');if(m[0]==='ROOM'){if(reconnecting){if(currentRoom===m[1]&&token)send('JOIN:'+(savedName||'Игрок')+':'+token);else{token='';savedName='';sessionStorage.removeItem('wigo-token');sessionStorage.removeItem('wigo-name');sessionStorage.removeItem('wigo-room');selfId=-1;joined=false;$('name').value='';$('join').hidden=false;$('lobby').hidden=true;$('scenario').hidden=true;$('game').hidden=true;$('finished').hidden=true;$('status').textContent='Новая комната. Введите имя.'}}currentRoom=m[1];sessionStorage.setItem('wigo-room',currentRoom);reconnecting=false}
else if(m[0]==='GAME')setGameTitle(m[1]);
else if(m[0]==='WELCOME'){token=m[2];selfId=Number(m[3]);joined=true;currentRoom=m[1];sessionStorage.setItem('wigo-token',token);sessionStorage.setItem('wigo-name',savedName||'Игрок');sessionStorage.setItem('wigo-room',currentRoom);$('room').textContent=m[1];$('join').hidden=true;$('status').textContent='Вы в комнате '+m[1]}
else if(m[0]==='STATE'){let d=JSON.parse(m.slice(1).join('|'));renderState(d)}
else if(m[0]==='SCENARIO'){showScenario(m)}
else if(m[0]==='PROFILE'){showProfile(m)}
else if(m[0]==='VOTE'){showVotes(m)}
else if(m[0]==='BOARD'){boardOpen=true;$('boardSection').hidden=false;renderBoard(lastState)}
else if(m[0]==='REVEALED'){revealedCards[m[1]+':'+m[2]]=m.slice(3).join('|');renderBoard(lastState)}
else if(m[0]==='WORD'){$('crocWord').querySelector('strong').textContent=m.slice(1).join('|')}
else if(m[0]==='AWORD'){$('aliasWord').querySelector('strong').textContent=m.slice(1).join('|')}
else if(m[0]==='ROLE')showMafiaRole(m.slice(1).join('|'));
else if(m[0]==='SPY_ROLE')showSpyRole(m)
else if(m[0]==='ACTION')showMafiaActions(m);
else if(m[0]==='SPY_OPTIONS')showSpyOptions(m.slice(1).join('|'))
else if(m[0]==='WHO_COUNTDOWN')showWhoCountdown(Number(m[1]));
else if(m[0]==='WHO_WORD')showWhoWord(m.slice(1).join('|'));
else if(m[0]==='HOST_ROLES')showMafiaHostRoles(m.slice(1).join('|'));
else if(m[0]==='HOST'){$('hostReminder').textContent=m.slice(1).join('|');$('hostReminder').hidden=false}
else if(m[0]==='RESULT'){const msg=m.slice(1).join('|');if(lastState&&lastState.game==='crocodile')$('crocProgress').textContent=msg;else if(lastState&&lastState.game==='alias')$('aliasProgress').textContent=msg;else if(lastState&&lastState.game==='mafia')$('mafiaFeedback').textContent=msg;else if(lastState&&lastState.game==='spy')$('spyFeedback').textContent=msg;else $('feedback').textContent=msg;}
else if(m[0]==='ERROR')$('status').textContent=m.slice(1).join('|');};}
function send(s){if(ws&&ws.readyState===1)ws.send(s)}
function joinRoom(){let n=$('name').value.trim()||'Игрок';savedName=n;sessionStorage.setItem('wigo-name',n);send('JOIN:'+n+':'+token)}
function setGameTitle(game){const name=game==='crocodile'?'Крокодил':game==='mafia'?'Мафия':game==='alias'?'Алиас':game==='spy'?'Кто шпион?':game==='whoami'?'Кто я?':'Бункер';$('title').textContent=name;document.title='WIGO · '+name}
function whoCardsKey(){return 'wigo-who-cards-'+currentRoom}
function readWhoCards(){try{return JSON.parse(sessionStorage.getItem(whoCardsKey())||'{}')}catch(_){return {}}}
function saveWhoCards(cards){sessionStorage.setItem(whoCardsKey(),JSON.stringify(cards))}
function renderWhoTargets(players){const active=players.filter(p=>p.connected&&p.id!==selfId);const key=active.map(p=>p.id+':'+p.name).join('|');if(key===whoRosterKey)return;if(whoRosterKey&&key!==whoRosterKey){sessionStorage.removeItem(whoCardsKey());sessionStorage.removeItem(whoCardsKey()+'-sent');whoCardSent=false;$('whoSubmitButton').disabled=false;$('whoCardStatus').textContent='Состав участников изменился — заполни карточки заново.'}const saved=readWhoCards(),box=$('whoTargets');box.replaceChildren();whoRosterKey=key;active.forEach(p=>{const label=document.createElement('label');label.className='small';label.textContent='Персонаж для игрока «'+p.name+'»';const input=document.createElement('input');input.maxLength=20;input.placeholder='Например: Шерлок Холмс';input.value=saved[p.id]||'';input.id='whoTarget'+p.id;input.disabled=whoCardSent;input.oninput=()=>{const cards=readWhoCards();cards[p.id]=input.value;saveWhoCards(cards)};box.append(label,input)})}
function submitWhoCards(){const players=lastState?lastState.players.filter(p=>p.connected&&p.id!==selfId):[],cards=readWhoCards();for(const p of players){const input=$('whoTarget'+p.id);const value=input?input.value.trim():cards[p.id]||'';if(!value){$('whoCardStatus').textContent='Придумай персонажа для каждого другого игрока.';if(input)input.focus();return}cards[p.id]=value}saveWhoCards(cards);players.forEach(p=>send('WHO_CARD:'+p.id+':'+cards[p.id]));whoCardSent=true;sessionStorage.setItem(whoCardsKey()+'-sent','1');$('whoTargets').querySelectorAll('input').forEach(input=>input.disabled=true);$('whoSubmitButton').disabled=true;$('whoCardStatus').textContent='Персонажи отправлены. Нажми «Готов», когда остальные закончат.'}
function resendWhoCards(players){const cards=readWhoCards();players.filter(p=>p.connected&&p.id!==selfId).forEach(p=>{if(cards[p.id])send('WHO_CARD:'+p.id+':'+cards[p.id])});whoCardSent=true;$('whoTargets').querySelectorAll('input').forEach(input=>input.disabled=true)}
function showWhoCountdown(ms){clearInterval(whoCountdownTimer);$('whoamiStart').disabled=true;$('whoamiWord').textContent='Готовься…';$('whoamiTitle').textContent='Переверни телефон';const end=Date.now()+Math.max(0,ms);const update=()=>{const left=Math.max(0,end-Date.now());$('whoamiCountdown').textContent=left?'Откроется через '+Math.ceil(left/1000)+'…':'Секунду…';if(!left)clearInterval(whoCountdownTimer)};update();whoCountdownTimer=setInterval(update,200)}
function showWhoWord(word){clearInterval(whoCountdownTimer);$('whoamiTitle').textContent='Кто ты?';$('whoamiWord').textContent=word||'Твой персонаж';$('whoamiCountdown').textContent='Не подглядывай! Остальные игроки должны увидеть карточку.';$('whoamiHelp').textContent='Задавай вопросы, на которые можно ответить «да» или «нет», и угадай своего персонажа.';$('whoamiStart').hidden=true}
function renderState(d){lastState=d;$('room').textContent=d.room;setGameTitle(d.game);$('players').replaceChildren();d.players.forEach(p=>{let row=document.createElement('div');row.className='player';let name=document.createElement('span');name.textContent=p.name+(p.id===d.host?' · ведущий':'');let tag=document.createElement('span');tag.className='tag '+(p.ready?'':'wait');tag.textContent=!p.connected?'нет связи':(p.alive?(p.ready?'готов':'не готов'):'выбыл');row.append(name,tag);$('players').append(row)});
let me=d.players.find(p=>p.id===selfId);if(me)$('readyButton').textContent=me.ready?'Снять готовность':'Готов';$('minimumPlayers').textContent=d.game==='crocodile'?'Одиночная игра: нужен один готовый игрок.':d.game==='alias'?'Алиас: один телефон передаётся объясняющему.':d.game==='whoami'?'Нужно минимум два игрока. Каждый предлагает персонажа для каждого другого участника.':'Для этой игры нужно минимум три готовых игрока.';
const ended=d.finished;$('join').hidden=true;$('lobby').hidden=d.running||ended;$('whoSubmit').hidden=d.game!=='whoami'||d.running||ended;if(d.game==='whoami'&&!d.running){renderWhoTargets(d.players);if(sessionStorage.getItem(whoCardsKey()+'-sent')==='1'&&!whoCardSent){resendWhoCards(d.players);$('whoSubmitButton').disabled=true;$('whoCardStatus').textContent='Твои предложения отправлены. Теперь нажми «Готов».'}}$('scenario').hidden=d.game!=='bunker'||!(d.running||ended);$('game').hidden=!d.running||d.game!=='bunker';$('boardSection').hidden=!(boardOpen&&d.game==='bunker');$('crocodileGame').hidden=!d.running||d.game!=='crocodile';$('aliasGame').hidden=!d.running||d.game!=='alias';$('mafiaGame').hidden=!d.running||d.game!=='mafia';$('spyGame').hidden=!d.running||d.game!=='spy';$('whoamiGame').hidden=!d.running||d.game!=='whoami';if(d.game==='whoami'&&!d.running){$('whoamiTitle').textContent='Подготовь телефон';$('whoamiWord').textContent='Сначала подготовь телефон';$('whoamiCountdown').textContent='';$('whoamiStart').hidden=false;$('whoamiStart').disabled=false;$('whoamiHelp').textContent='Нажми кнопку, переверни телефон экраном к остальным и поднеси его ко лбу. Через 5 секунд появится персонаж — не подглядывай!'};$('finished').hidden=!ended;
if(d.running&&d.game==='bunker'){$('round').textContent='Раунд '+d.round;const current=d.players.find(p=>p.id===d.revealer);$('phaseName').textContent=d.phase==='voting'?'Голосование':(d.phase==='reveal'?'Раскрытие карточек':'Обсуждение');$('turnNotice').hidden=d.phase!=='reveal';if(d.phase==='reveal')$('turnNotice').textContent=current?(current.id===selfId?'ТВОЙ ХОД. Открой карточки и нажми зелёную закрытую карту.':'Сейчас раскрывает '+current.name+'.'):'Ожидаем игрока.';$('hostAction').hidden=d.phase!=='discussion'||d.host!==selfId;if(d.phase!=='voting')$('votes').replaceChildren();if(boardOpen)renderBoard(d)}
if(d.running&&d.game==='crocodile'){$('crocTimer').textContent=Math.ceil((d.crocMs||0)/1000)+' сек';$('crocScore').textContent='Угадано: '+d.crocScore;$('crocProgress').textContent='Слово '+d.crocPlayed+' из '+d.crocTotal+'. Слова в этой игре не повторяются.'}
if(d.running&&d.game==='alias'){$('aliasTimer').textContent=Math.ceil((d.aliasMs||0)/1000)+' сек';$('aliasScore').textContent='Угадано: '+d.aliasScore;$('aliasProgress').textContent='Слово '+d.aliasPlayed+' из '+d.aliasTotal+'. Слова не повторяются.'}
if(d.running&&d.game==='mafia'){$('mafiaPhase').textContent=d.phase==='voting'?'День · голосование':d.phase==='day'?'День':'Ночь';$('mafiaRound').textContent='Цикл '+d.mafiaRound;const controls=$('mafiaHostAction');controls.replaceChildren();controls.hidden=d.host!==selfId||d.phase==='voting';if(d.host===selfId&&d.phase==='night')addHostButton(controls,'Объявить день','M_DAY');if(d.host===selfId&&d.phase==='day'){addHostButton(controls,'Объявить ночь','M_NIGHT','secondary');addHostButton(controls,'Открыть голосование','M_VOTE_START')}$('hostPanel').hidden=d.host!==selfId;if(d.phase!=='voting'){$('mafiaActions').replaceChildren();$('mafiaActions').hidden=true}else $('mafiaActions').hidden=$('mafiaActions').childElementCount===0;if(d.host===selfId){renderMafiaHostRoles();if(d.mafiaLastEliminated){$('hostReminder').textContent='Напоминание ведущему: '+d.mafiaLastEliminated+' выбыл. Его роль — '+d.mafiaLastRole+'. Отметь выбывшего и сообщи игрокам.';$('hostReminder').hidden=false}}}
if(d.running&&d.game==='spy'){$('spyPhase').textContent=d.phase==='voting'?'Голосование':'Обсуждение';$('spyRound').textContent='Участников: '+d.players.filter(p=>p.alive).length;const controls=$('spyHostAction');controls.replaceChildren();controls.hidden=d.host!==selfId||d.phase!=='discussion';if(d.host===selfId&&d.phase==='discussion')addHostButton(controls,'Начать голосование','SPY_VOTE_START');if(d.phase!=='voting'){$('spyActions').replaceChildren();$('spyActions').hidden=true}else $('spyActions').hidden=$('spyActions').childElementCount===0}
if(!d.running&&!ended){boardOpen=false;$('boardSection').hidden=true;for(const k in revealedCards)delete revealedCards[k]}
if(ended){$('finished').className='result win';$('winners').replaceChildren();if(d.game==='bunker'){$('resultIcon').textContent='В БУНКЕРЕ ОСТАЛИСЬ ДВОЕ';$('resultTitle').textContent='Победа!';$('resultMessage').textContent='Победители — два игрока, оставшиеся в бункере:';d.players.filter(p=>p.alive).forEach(p=>addWinner(p.name))}else if(d.game==='crocodile'||d.game==='alias'){$('resultIcon').textContent=d.game==='alias'?'АЛИАС':'КРОКОДИЛ';$('resultTitle').textContent='Раунд завершён';const score=d.game==='alias'?d.aliasScore:d.crocScore;const played=d.game==='alias'?d.aliasPlayed:d.crocPlayed;$('resultMessage').textContent='Угадано '+score+' из '+played+' слов.'}else if(d.game==='spy'){$('resultIcon').textContent='КТО ШПИОН?';$('resultTitle').textContent=d.spyWinner==='spy'?'Победил шпион':'Победили остальные игроки';$('resultMessage').textContent='Партия завершена.'}else{$('resultIcon').textContent='МАФИЯ';$('resultTitle').textContent=d.mafiaWinner==='mafia'?'Победила мафия':'Победили мирные жители';$('resultMessage').textContent='Партия завершена.';if(d.mafiaWinner==='town')d.players.filter(p=>p.alive).forEach(p=>addWinner(p.name))}}}
function addWinner(name){let row=document.createElement('div');row.className='player';row.textContent='🏆 '+name;$('winners').append(row)}
function addHostButton(box,label,command,kind=''){const b=document.createElement('button');b.textContent=label;if(kind)b.className=kind;b.onclick=()=>send(command);box.append(b)}
function showMafiaActions(m){const box=$('mafiaActions');box.replaceChildren();box.hidden=false;const options=m.slice(2).join('|').split(',').filter(Boolean);options.forEach(item=>{const pair=item.split(':');const b=document.createElement('button');b.className='secondary';b.textContent='Голосовать за '+pair.slice(1).join(':');b.onclick=()=>{box.replaceChildren();box.hidden=true;send('M_VOTE:'+pair[0])};box.append(b)})}
function showMafiaRole(role){$('mafiaRole').textContent=role;$('mafiaHelp').textContent=(role==='Мафия'?'Твоя задача — вычислить мирных жителей и пережить голосования.':'Обсуждай подозрения и помоги голосованием найти мафию.')+(lastState&&lastState.host===selfId?' Тебе как ведущему также доступны все карточки группы ниже.':' Карточку видишь только ты.')}
function showSpyRole(m){const spy=m[1]==='spy';$('spyRole').textContent=spy?'ТЫ ШПИОН':'ТЫ НЕ ШПИОН';$('spySecret').textContent=spy?'Тайное место тебе неизвестно. Слушай вопросы и не выдавай себя.':'Тайное место: '+(m.slice(2).join('|')||'—')+'. Не показывай карточку другим.'}
function showSpyOptions(raw){const box=$('spyActions');box.replaceChildren();box.hidden=false;raw.split(',').filter(Boolean).forEach(item=>{const pair=item.split(':');const b=document.createElement('button');b.className='secondary';b.textContent='Голосовать за '+pair.slice(1).join(':');b.onclick=()=>{box.replaceChildren();box.hidden=true;send('SPY_VOTE:'+pair[0])};box.append(b)})}
function showMafiaHostRoles(raw){mafiaHostRoles=raw.split(',').filter(Boolean).map(x=>{const a=x.split(':');return{id:Number(a[0]),name:a[1]||'Игрок',role:a.slice(2).join(':')}});renderMafiaHostRoles()}
function renderMafiaHostRoles(){const box=$('mafiaHostRoles');if(!box)return;box.replaceChildren();mafiaHostRoles.forEach(r=>{const p=lastState&&lastState.players.find(x=>x.id===r.id);const row=document.createElement('article');row.className='hostRoleCard';const name=document.createElement('span');name.textContent=r.name+(p&&!p.alive?' · ВЫБЫЛ':' · В ИГРЕ');const role=document.createElement('strong');role.textContent=r.role;row.append(name,role);box.append(row)})}
function renderBoard(d){if(!boardOpen||!d)return;const names=new Map(d.players.map(p=>[p.id,p.name]));const current=names.get(d.revealer);$('revealQueue').textContent=d.phase==='reveal'&&d.queue.length?'СЕЙЧАС ХОДИТ: '+(current||'игрок')+'. '+(d.revealer===selfId?'Нажми на одну из своих зелёных карточек «ОТКРЫТЬ КАРТУ».':'Ждём, пока '+current+' нажмёт на закрытую карточку.')+' Очередь: '+d.queue.map((id,i)=>(i===0?'▶ ':'')+(names.get(id)||'Игрок')).join(' → '):(d.phase==='reveal'?'Ожидаем игрока…':'Очередь раскрытия завершена. Можно обсуждать открытые карточки.');const box=$('cardBoard');box.replaceChildren();d.players.forEach(p=>{const myTurn=p.id===selfId&&p.id===d.revealer&&d.phase==='reveal';const panel=document.createElement('article');panel.className='playerBoard'+(p.id===d.revealer&&d.phase==='reveal'?' currentTurn':'');const heading=document.createElement('h3');heading.textContent=p.name;const label=document.createElement('span');label.className='tag';label.textContent=p.id===d.revealer&&d.phase==='reveal'?(p.id===selfId?'ТВОЙ ХОД':'СЕЙЧАС ХОД'): (p.id===selfId?'ТЫ':'ОЖИДАЕТ');heading.append(label);panel.append(heading);const grid=document.createElement('div');grid.className='cardGrid';cardNames.forEach((n,i)=>{const key=p.id+':'+i;const open=Object.prototype.hasOwnProperty.call(revealedCards,key);let card;if(open){card=document.createElement('article');card.className='cardOpen';const cat=document.createElement('span');cat.textContent=n;const val=document.createElement('strong');val.textContent=revealedCards[key];card.append(cat,val)}else{card=document.createElement(myTurn?'button':'article');card.className='cardBack '+(myTurn?'canReveal':'waiting');const cat=document.createElement('span');cat.textContent=n;const val=document.createElement('strong');val.textContent=myTurn?'НАЖМИ, ЧТОБЫ ОТКРЫТЬ':'ЗАКРЫТА · ЖДЁТ ОЧЕРЕДИ';card.append(cat,val);if(myTurn)card.onclick=()=>send('REVEAL:'+i)}grid.append(card)});panel.append(grid);box.append(panel)})}
function showScenario(m){$('scenarioTitle').textContent=m[1];$('scenarioDescription').textContent=m[2];$('capacity').textContent='Условие победы: остаться вдвоём'}
function showProfile(m){let box=$('profile');box.replaceChildren();for(let i=1;i+1<m.length;i+=2){let card=document.createElement('article');card.className='trait';let label=document.createElement('span');label.textContent=m[i];let value=document.createElement('strong');value.textContent=m[i+1];card.append(label,value);box.append(card)}}
function showVotes(m){let box=$('votes');box.replaceChildren();m.slice(1).join('|').split(',').filter(Boolean).forEach(item=>{let pair=item.split(':');let button=document.createElement('button');button.className='secondary';button.textContent='Голосовать за '+pair.slice(1).join(':');button.onclick=()=>send('VOTE:'+pair[0]);box.append(button)})}
connect();
</script></main></body></html>
)HTML";
